-- ============================================================
-- SafeDrive – Supabase PostgreSQL Schema
-- Run this in the Supabase SQL Editor (Dashboard → SQL Editor)
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- 0. Extensions
-- ────────────────────────────────────────────────────────────
create extension if not exists "uuid-ossp";

-- ────────────────────────────────────────────────────────────
-- 1. USER PROFILES
--    Extended user data beyond what Supabase Auth stores.
-- ────────────────────────────────────────────────────────────
create table if not exists public.user_profiles (
  id            uuid primary key references auth.users (id) on delete cascade,
  first_name    text,
  last_name     text,
  phone         text,
  address       text,
  postcode      text,
  date_of_birth text,               -- stored as DD/MM/YYYY string to match app input
  licence_type  text,               -- Full UK | Provisional | International | European
  avatar_url    text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- Auto-update updated_at on any row change
create or replace function public.handle_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_user_profiles_updated on public.user_profiles;
create trigger on_user_profiles_updated
  before update on public.user_profiles
  for each row execute procedure public.handle_updated_at();

-- Automatically create a profile row when a new auth user is created
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer as $$
begin
  insert into public.user_profiles (id, first_name, last_name)
  values (
    new.id,
    new.raw_user_meta_data ->> 'first_name',
    new.raw_user_meta_data ->> 'last_name'
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ────────────────────────────────────────────────────────────
-- 2. VEHICLES
--    Reusable vehicle records linked to a user.
-- ────────────────────────────────────────────────────────────
create table if not exists public.vehicles (
  id              uuid primary key default uuid_generate_v4(),
  user_id         uuid not null references auth.users (id) on delete cascade,
  registration    text not null,
  make            text,
  model           text,
  year            text,
  fuel_type       text,             -- Petrol | Diesel | Electric | Hybrid
  car_category    text,             -- City Car | Small Hatchback | … | Van / MPV
  annual_mileage  integer,
  created_at      timestamptz not null default now()
);

create index if not exists vehicles_user_id_idx on public.vehicles (user_id);

-- ────────────────────────────────────────────────────────────
-- 3. QUOTES
--    Every price estimate generated by the app.
-- ────────────────────────────────────────────────────────────
create table if not exists public.quotes (
  id                uuid primary key default uuid_generate_v4(),
  user_id           uuid references auth.users (id) on delete cascade,

  -- Personal details snapshot
  first_name        text,
  last_name         text,
  dob               text,
  phone             text,
  address           text,
  postcode          text,
  licence_type      text,

  -- Vehicle details snapshot
  car_registration  text,
  car_make          text,
  car_model         text,
  car_year          text,
  annual_mileage    text,
  fuel_type         text,
  car_usage         text,           -- Social only | Social & commuting | Business use
  no_claims_years   text,
  car_category      text,

  -- Quote parameters
  cover_type        text not null default 'Comprehensive',
  voluntary_excess  text,

  -- Calculated premiums (£)
  annual_quote      numeric(10,2),
  monthly_quote     numeric(10,2),

  created_at        timestamptz not null default now()
);

create index if not exists quotes_user_id_idx       on public.quotes (user_id);
create index if not exists quotes_created_at_idx    on public.quotes (created_at desc);

-- ────────────────────────────────────────────────────────────
-- 4. POLICIES
--    Purchased policies converted from a saved quote.
-- ────────────────────────────────────────────────────────────
create table if not exists public.policies (
  id                  uuid primary key default uuid_generate_v4(),
  user_id             uuid not null references auth.users (id) on delete cascade,
  quote_id            uuid references public.quotes (id) on delete set null,

  policy_number       text unique not null,   -- e.g. SD-2024-XXXXXX

  -- Cover details
  cover_type          text not null,
  car_registration    text,
  car_make            text,
  car_model           text,
  car_year            text,
  car_category        text,
  voluntary_excess    text,

  -- Driver details snapshot
  insured_name        text,
  postcode            text,
  licence_type        text,

  -- Financials
  annual_premium      numeric(10,2),
  monthly_premium     numeric(10,2),
  payment_frequency   text default 'annual',  -- annual | monthly

  -- Status & dates
  status              text not null default 'active',  -- active | expired | cancelled | pending
  start_date          date not null default current_date,
  end_date            date not null default (current_date + interval '1 year'),

  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

drop trigger if exists on_policies_updated on public.policies;
create trigger on_policies_updated
  before update on public.policies
  for each row execute procedure public.handle_updated_at();

create index if not exists policies_user_id_idx on public.policies (user_id);
create index if not exists policies_status_idx  on public.policies (status);

-- ────────────────────────────────────────────────────────────
-- 5. CLAIMS
--    Claims submitted against an active policy.
-- ────────────────────────────────────────────────────────────
create table if not exists public.claims (
  id              uuid primary key default uuid_generate_v4(),
  user_id         uuid not null references auth.users (id) on delete cascade,
  policy_id       uuid references public.policies (id) on delete set null,

  claim_number    text unique not null,   -- e.g. CLM-2024-XXXXXX
  claim_type      text not null,          -- Accident / Collision | Theft | Fire Damage | …

  -- Incident details
  incident_date   date not null,
  incident_location text,
  description     text not null,

  -- Financials
  estimated_cost  numeric(10,2),
  settlement_amount numeric(10,2),

  -- Status
  status          text not null default 'submitted',
                                          -- submitted | under_review | approved | rejected | settled
  notes           text,

  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

drop trigger if exists on_claims_updated on public.claims;
create trigger on_claims_updated
  before update on public.claims
  for each row execute procedure public.handle_updated_at();

create index if not exists claims_user_id_idx   on public.claims (user_id);
create index if not exists claims_policy_id_idx on public.claims (policy_id);
create index if not exists claims_status_idx    on public.claims (status);

-- ────────────────────────────────────────────────────────────
-- 6. ROW LEVEL SECURITY (RLS)
--    Each user can only see and modify their own rows.
-- ────────────────────────────────────────────────────────────

-- user_profiles
alter table public.user_profiles enable row level security;

drop policy if exists "Users can view own profile"   on public.user_profiles;
drop policy if exists "Users can update own profile" on public.user_profiles;
create policy "Users can view own profile"
  on public.user_profiles for select
  using (auth.uid() = id);
create policy "Users can update own profile"
  on public.user_profiles for update
  using (auth.uid() = id);

-- vehicles
alter table public.vehicles enable row level security;

drop policy if exists "Users can view own vehicles"   on public.vehicles;
drop policy if exists "Users can insert own vehicles" on public.vehicles;
drop policy if exists "Users can update own vehicles" on public.vehicles;
drop policy if exists "Users can delete own vehicles" on public.vehicles;
create policy "Users can view own vehicles"
  on public.vehicles for select
  using (auth.uid() = user_id);
create policy "Users can insert own vehicles"
  on public.vehicles for insert
  with check (auth.uid() = user_id);
create policy "Users can update own vehicles"
  on public.vehicles for update
  using (auth.uid() = user_id);
create policy "Users can delete own vehicles"
  on public.vehicles for delete
  using (auth.uid() = user_id);

-- quotes
alter table public.quotes enable row level security;

drop policy if exists "Users can view own quotes"   on public.quotes;
drop policy if exists "Users can insert own quotes" on public.quotes;
drop policy if exists "Users can delete own quotes" on public.quotes;
create policy "Users can view own quotes"
  on public.quotes for select
  using (auth.uid() = user_id);
create policy "Users can insert own quotes"
  on public.quotes for insert
  with check (auth.uid() = user_id);
create policy "Users can delete own quotes"
  on public.quotes for delete
  using (auth.uid() = user_id);

-- policies
alter table public.policies enable row level security;

drop policy if exists "Users can view own policies"   on public.policies;
drop policy if exists "Users can insert own policies" on public.policies;
drop policy if exists "Users can update own policies" on public.policies;
create policy "Users can view own policies"
  on public.policies for select
  using (auth.uid() = user_id);
create policy "Users can insert own policies"
  on public.policies for insert
  with check (auth.uid() = user_id);
create policy "Users can update own policies"
  on public.policies for update
  using (auth.uid() = user_id);

-- claims
alter table public.claims enable row level security;

drop policy if exists "Users can view own claims"   on public.claims;
drop policy if exists "Users can insert own claims" on public.claims;
drop policy if exists "Users can update own claims" on public.claims;
create policy "Users can view own claims"
  on public.claims for select
  using (auth.uid() = user_id);
create policy "Users can insert own claims"
  on public.claims for insert
  with check (auth.uid() = user_id);
create policy "Users can update own claims"
  on public.claims for update
  using (auth.uid() = user_id);

-- ────────────────────────────────────────────────────────────
-- 7. HELPER FUNCTION: generate_policy_number()
-- ────────────────────────────────────────────────────────────
create or replace function public.generate_policy_number()
returns text language plpgsql as $$
declare
  chars  text    := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  result text    := '';
  i      integer := 0;
begin
  for i in 1..6 loop
    result := result || substr(chars, floor(random() * length(chars) + 1)::int, 1);
  end loop;
  return 'SD-' || to_char(now(), 'YYYY') || '-' || result;
end;
$$;

-- ────────────────────────────────────────────────────────────
-- 8. HELPER FUNCTION: generate_claim_number()
-- ────────────────────────────────────────────────────────────
create or replace function public.generate_claim_number()
returns text language plpgsql as $$
declare
  result text := '';
  i      integer := 0;
  chars  text := '0123456789ABCDEFGHJKLMNPQRSTUVWXYZ';
begin
  for i in 1..7 loop
    result := result || substr(chars, floor(random() * length(chars) + 1)::int, 1);
  end loop;
  return 'CLM-' || to_char(now(), 'YYYY') || '-' || result;
end;
$$;
